# Generated by Django 5.2.11 on 2026-02-13 19:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("po", "0002_poline"),
    ]

    operations = [
        migrations.CreateModel(
            name="ERPSnapshot",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("snapshot_timestamp", models.DateTimeField(db_index=True)),
                ("run_identifier", models.CharField(db_index=True, max_length=64)),
                ("po_number", models.CharField(max_length=64)),
                ("line_number", models.PositiveIntegerField()),
                ("sku", models.CharField(max_length=128)),
                ("item", models.CharField(max_length=255)),
                ("ordered_quantity", models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ("delivered_quantity", models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ("remaining_quantity", models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ("promised_date", models.DateField(blank=True, null=True)),
                ("current_status", models.CharField(blank=True, default="", max_length=64)),
                ("po_insert_date", models.DateField(blank=True, null=True)),
                ("final_customer", models.CharField(blank=True, default="", max_length=255)),
                ("source_quality", models.CharField(blank=True, default="", max_length=16)),
                ("last_update_timestamp", models.DateTimeField(blank=True, null=True)),
                ("is_stale", models.BooleanField(default=False)),
                ("staleness_checked_at", models.DateTimeField(blank=True, null=True)),
                ("custom_date_1", models.DateField(blank=True, null=True)),
                ("custom_date_2", models.DateField(blank=True, null=True)),
                ("custom_date_3", models.DateField(blank=True, null=True)),
                ("custom_date_4", models.DateField(blank=True, null=True)),
                ("custom_date_5", models.DateField(blank=True, null=True)),
                ("custom_text_1", models.CharField(blank=True, max_length=255, null=True)),
                ("custom_text_2", models.CharField(blank=True, max_length=255, null=True)),
                ("custom_text_3", models.CharField(blank=True, max_length=255, null=True)),
                ("custom_text_4", models.CharField(blank=True, max_length=255, null=True)),
                ("custom_text_5", models.CharField(blank=True, max_length=255, null=True)),
                ("custom_decimal_1", models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ("custom_decimal_2", models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ("custom_decimal_3", models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ("custom_decimal_4", models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ("custom_decimal_5", models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ("custom_column_sources", models.JSONField(blank=True, default=dict)),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="erp_snapshots",
                        to="po.supplier",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("run_identifier", "po_number", "line_number"),
                        name="ing_snapshot_run_po_line_unique",
                    )
                ],
                "indexes": [
                    models.Index(fields=["po_number", "line_number"], name="ing_snapshot_po_line_idx"),
                    models.Index(fields=["snapshot_timestamp"], name="ing_snapshot_time_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ItemXref",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("erp_item_code", models.CharField(max_length=128)),
                ("mapped_sku", models.CharField(max_length=128)),
                ("mapped_item", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "supplier",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="item_xrefs", to="po.supplier"),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("supplier", "erp_item_code"),
                        name="ing_itemxref_supplier_erp_item_unique",
                    )
                ]
            },
        ),
        migrations.CreateModel(
            name="ERPChangeEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("field_name", models.CharField(max_length=128)),
                ("previous_value", models.TextField(blank=True, null=True)),
                ("new_value", models.TextField(blank=True, null=True)),
                ("detected_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                (
                    "po_line",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="erp_change_events",
                        to="po.poline",
                    ),
                ),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="change_events",
                        to="ingestion.erpsnapshot",
                    ),
                ),
            ],
        ),
    ]
