# Generated by Django 5.2.11 on 2026-02-13 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='erpsnapshot',
            name='in_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
