# Generated by Django 5.2.11 on 2026-02-13 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('po', '0002_poline'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivered_quantity', models.DecimalField(decimal_places=3, max_digits=18)),
                ('delivery_date', models.DateField()),
                ('source', models.CharField(choices=[('ingestion', 'Ingestion'), ('manual', 'Manual')], default='ingestion', max_length=16)),
                ('run_identifier', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('po_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='po.poline')),
            ],
            options={
                'indexes': [models.Index(fields=['delivery_date'], name='bat_deliv_date_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(source='ingestion'), fields=('po_line', 'run_identifier'), name='batches_batch_poline_run_ingestion_unique')],
            },
        ),
    ]
