# Generated by Django 5.2.11 on 2026-02-13 19:55

import django.db.models.deletion
from django.db import migrations, models

import apps.audit.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("po", "0002_poline"),
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("event_type", models.CharField(max_length=64)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("bulk", "Bulk"),
                            ("inline", "Inline"),
                            ("ingestion", "Ingestion"),
                            ("system", "System"),
                        ],
                        max_length=16,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("previous_values", models.JSONField(blank=True, default=dict)),
                ("new_values", models.JSONField(blank=True, default=dict)),
                ("reason", models.TextField(blank=True, default="")),
                (
                    "po_line",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_events",
                        to="po.poline",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_events",
                        to="accounts.user",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["event_type", "timestamp"], name="audit_type_time_idx"),
                ]
            },
            managers=[
                ("objects", apps.audit.models.AppendOnlyAuditManager()),
            ],
        ),
    ]
