# Generated by Django 5.2.11 on 2026-02-13 19:55

import django.db.models.deletion
from django.db import migrations, models

import apps.core.querysets


class Migration(migrations.Migration):

    dependencies = [
        ("po", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="POLine",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("po_number", models.CharField(max_length=64)),
                ("line_number", models.PositiveIntegerField()),
                ("sku", models.CharField(max_length=128)),
                ("item", models.CharField(max_length=255)),
                ("ordered_quantity", models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ("delivered_quantity", models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ("remaining_quantity", models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ("promised_date", models.DateField(blank=True, null=True)),
                ("current_status", models.CharField(blank=True, default="", max_length=64)),
                ("po_insert_date", models.DateField(blank=True, null=True)),
                ("final_customer", models.CharField(blank=True, default="", max_length=255)),
                (
                    "source_quality",
                    models.CharField(
                        choices=[("erp", "ERP"), ("user", "User"), ("mixed", "Mixed")],
                        default="erp",
                        max_length=16,
                    ),
                ),
                ("last_update_timestamp", models.DateTimeField(blank=True, null=True)),
                ("is_stale", models.BooleanField(default=False)),
                ("staleness_checked_at", models.DateTimeField(blank=True, null=True)),
                ("custom_date_1", models.DateField(blank=True, null=True)),
                ("custom_date_2", models.DateField(blank=True, null=True)),
                ("custom_date_3", models.DateField(blank=True, null=True)),
                ("custom_date_4", models.DateField(blank=True, null=True)),
                ("custom_date_5", models.DateField(blank=True, null=True)),
                ("custom_text_1", models.CharField(blank=True, max_length=255, null=True)),
                ("custom_text_2", models.CharField(blank=True, max_length=255, null=True)),
                ("custom_text_3", models.CharField(blank=True, max_length=255, null=True)),
                ("custom_text_4", models.CharField(blank=True, max_length=255, null=True)),
                ("custom_text_5", models.CharField(blank=True, max_length=255, null=True)),
                ("custom_decimal_1", models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ("custom_decimal_2", models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ("custom_decimal_3", models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ("custom_decimal_4", models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ("custom_decimal_5", models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ("custom_column_sources", models.JSONField(blank=True, default=dict)),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="po_lines",
                        to="po.supplier",
                    ),
                ),
            ],
            managers=[
                ("objects", apps.core.querysets.ScopedManager()),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("po_number", "line_number"),
                        name="po_poline_po_number_line_number_unique",
                    )
                ],
            },
        ),
    ]
